FROM hadoop-hive-spark-base AS base
FROM nvidia/cuda:12.8.0-cudnn-devel-ubuntu24.04
SHELL ["/bin/bash", "-i", "-c"]

RUN sed -i -e "s|http://archive.ubuntu.com|http://eg.archive.ubuntu.com|g" /etc/apt/sources.list \
 && apt-get -qq update  \
 && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends \
    sudo \
    openjdk-8-jdk \
    curl \
    coreutils \
    libc6-dev \
    git\
    ca-certificates\
    gnupg\
    lsb-release\
    locales\
    python3-full\
    python3-dev\
    python3-pip\
    python3-setuptools\
    python3-wheel\
    python3-venv\
    python-is-python3\
 && locale-gen en_US.UTF-8\
 && rm -rf /var/lib/apt/lists/*
    
ARG USERNAME=jupyter
ARG GROUPNAME=jupyter
ARG UID=1001
ARG GID=1001

RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
 && chmod 0440 /etc/sudoers.d/$USERNAME \
 && groupadd -g $GID $GROUPNAME \
 && useradd -m -s /bin/bash -u $UID -g $GID $USERNAME

USER $USERNAME
ARG HOME=/home/$USERNAME
WORKDIR $HOME

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

# Hadoop
COPY --from=base --chown=$USERNAME:$GROUPNAME /opt/hadoop /opt/hadoop
ENV HADOOP_HOME=/opt/hadoop
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV PATH=$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$PATH
ENV LD_LIBRARY_PATH=$HADOOP_HOME/lib/native:$LD_LIBRARY_PATH

# Spark
COPY --from=base --chown=$USERNAME:$GROUPNAME /opt/spark /opt/spark
ENV SPARK_HOME=/opt/spark
ENV PYTHONHASHSEED=1
ENV PYSPARK_PYTHON=python3
ENV SPARK_CONF_DIR=$SPARK_HOME/conf
ENV PATH=$SPARK_HOME/sbin:$SPARK_HOME/bin:$PATH

# Hive
COPY --from=base --chown=$USERNAME:$GROUPNAME /opt/hive /opt/hive
ENV HIVE_HOME=/opt/hive
ENV HIVE_CONF_DIR=$HIVE_HOME/conf
ENV PATH=$HIVE_HOME/sbin:$HIVE_HOME/bin:$PATH

RUN echo "export LANG=en_US.UTF-8" >> "$HOME/.bashrc"

RUN python3 -m venv "$HOME/.venv"

RUN source "$HOME/.venv/bin/activate"\
 && pip install --default-timeout=10000 --no-cache-dir\
    unsloth\
    einops\
    packaging\
    ninja\
    findspark\
    notebook\
    traitlets\
    ipywidgets\
 && pip install --default-timeout=10000 --no-cache-dir --no-deps\
    flash-attn

COPY run.sh /usr/local/sbin/run.sh
RUN sudo chmod a+x /usr/local/sbin/run.sh
CMD ["run.sh"]